
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    # DOTNET

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Backend
      run: dotnet restore ./backend-api/backend-api.csproj

    - name: Build Backend
      run: dotnet build ./backend-api/backend-api.csproj --no-restore

    # ANGULAR

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Angular Packages
      run: |
        cd frontend-angular
        npm install

    - name: Build Angular
      run: |
        cd frontend-angular
        npm run build

    # DOCKER

    - name: Build Backend Docker Image
      run: docker build -t backend-api-image ./backend-api

    - name: Build Frontend Docker Image
      run: docker build -t frontend-angular-image ./frontend-angular